repos:
- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.9.0
  hooks:
  - id: reorder-python-imports
- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
  - id: black
    args: [--safe, --quiet, --line-length, "100"]
    language_version: python3
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: debug-statements
- repo: https://github.com/PyCQA/flake8
  rev: 6.0.0
  hooks:
  - id: flake8
    language_version: python3
    args: ["--ignore=E128,E811,W503,E203", "--max-line-length=100"]
- repo: https://github.com/asottile/pyupgrade
  rev: v3.3.0
  hooks:
  - id: pyupgrade
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.991
  hooks:
    - id: mypy
      language_version: python3
      additional_dependencies:
        - types-attrs
        - types-requests
        - attrs
        - requests
        - selenium
        - pytest
